/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class TebakNamaWindow extends javax.swing.JFrame {
    WordModel modelWord;    
    List<WordModel> bankSoal;
    /**
     * Creates new form TebakNamaWindow
     */
    
    String namaHasil;
    String namaAcakan;
    int nyawa;
    int hintTotal;
    public TebakNamaWindow() {
        initComponents();
        categoryButton1.setVisible(false);
        categoryButton2.setVisible(false);
        categoryButton3.setVisible(false);
        startButton.setVisible(true);
        messageLabel.setText("Click Start");
        nameTextField.setVisible(false);
        submitButton.setVisible(false);
        resetButton.setVisible(false);
        nyawaLabel.setVisible(false);
        hintButton.setVisible(false);
        categoryButton.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        nyawaLabel = new javax.swing.JLabel();
        hintButton = new javax.swing.JButton();
        categoryButton1 = new javax.swing.JButton();
        categoryButton2 = new javax.swing.JButton();
        categoryButton = new javax.swing.JButton();
        categoryButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/tebakNama.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        startButton.setBackground(new java.awt.Color(51, 255, 0));
        startButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 0));
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Click the start button !");

        nameLabel.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nameTextField.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        submitButton.setBackground(new java.awt.Color(51, 255, 0));
        submitButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 0));
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(51, 255, 0));
        resetButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 0));
        resetButton.setText("PLAY AGAIN");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        nyawaLabel.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        nyawaLabel.setText("jLabel2");

        hintButton.setBackground(new java.awt.Color(51, 255, 0));
        hintButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        hintButton.setForeground(new java.awt.Color(255, 255, 0));
        hintButton.setText("HINT");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        categoryButton1.setBackground(new java.awt.Color(51, 255, 0));
        categoryButton1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        categoryButton1.setForeground(new java.awt.Color(255, 255, 0));
        categoryButton1.setText("PEMAIN BOLA");
        categoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButton1ActionPerformed(evt);
            }
        });

        categoryButton2.setBackground(new java.awt.Color(51, 255, 0));
        categoryButton2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        categoryButton2.setForeground(new java.awt.Color(255, 255, 0));
        categoryButton2.setText("NARUTO");
        categoryButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButton2ActionPerformed(evt);
            }
        });

        categoryButton.setBackground(new java.awt.Color(51, 255, 0));
        categoryButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        categoryButton.setForeground(new java.awt.Color(255, 255, 0));
        categoryButton.setText("Change Category");
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });

        categoryButton3.setBackground(new java.awt.Color(51, 255, 0));
        categoryButton3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        categoryButton3.setForeground(new java.awt.Color(255, 255, 0));
        categoryButton3.setText("SETAN");
        categoryButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameTextField)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(nyawaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(categoryButton)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(categoryButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoryButton2)
                        .addGap(18, 18, 18)
                        .addComponent(categoryButton3)
                        .addGap(138, 138, 138))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(hintButton)
                            .addGap(230, 230, 230))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(startButton)
                            .addGap(227, 227, 227)))))
            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryButton1)
                    .addComponent(categoryButton2)
                    .addComponent(categoryButton3))
                .addGap(11, 11, 11)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nyawaLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hintButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(categoryButton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categoryButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButton3ActionPerformed
        // TODO add your handling code here:
        hintTotal = 3;
        bankSoal = WordGenerator.createQuestionInCollection3();
        int soalIndex = (int)Math.floor(Math.random()*bankSoal.size());
        modelWord = bankSoal.get(soalIndex);
        nameLabel.setVisible(true);
        messageLabel.setText("Type The Answer Of The Scribble Below");
        nameLabel.setText(modelWord.acakHuruf());
        startButton.setVisible(false);
        nameTextField.setVisible(true);
        submitButton.setVisible(true);
        nyawaLabel.setVisible(true);
        nyawa = 3;
        nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
        modelWord.setSoal(modelWord.getBasicWord());
        hintButton.setVisible(true);
        categoryButton1.setVisible(false);
        categoryButton2.setVisible(false);
        categoryButton3.setVisible(false);
        startButton.setVisible(false);
    }//GEN-LAST:event_categoryButton3ActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        // TODO add your handling code here:
        categoryButton.setVisible(false);
        categoryButton1.setVisible(true);
        categoryButton2.setVisible(true);
        categoryButton3.setVisible(true);
        startButton.setVisible(false);
        messageLabel.setText("Select Category");
        nameTextField.setVisible(false);
        submitButton.setVisible(false);
        resetButton.setVisible(false);
        nyawaLabel.setVisible(false);
        hintButton.setVisible(false);
        nameTextField.setText("");
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void categoryButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButton2ActionPerformed
        // TODO add your handling code here:
        hintTotal = 3;
        bankSoal = WordGenerator.createQuestionInCollection2();
        int soalIndex = (int)Math.floor(Math.random()*bankSoal.size());
        modelWord = bankSoal.get(soalIndex);
        nameLabel.setVisible(true);
        messageLabel.setText("Type The Answer Of The Scribble Below");
        nameLabel.setText(modelWord.acakHuruf());
        startButton.setVisible(false);
        nameTextField.setVisible(true);
        submitButton.setVisible(true);
        nyawaLabel.setVisible(true);
        nyawa = 3;
        nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
        modelWord.setSoal(modelWord.getBasicWord());
        hintButton.setVisible(true);
        categoryButton1.setVisible(false);
        categoryButton2.setVisible(false);
        categoryButton3.setVisible(false);
        startButton.setVisible(false);
    }//GEN-LAST:event_categoryButton2ActionPerformed

    private void categoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButton1ActionPerformed
        // TODO add your handling code here:
        hintTotal = 3;
        bankSoal = WordGenerator.createQuestionInCollection();
        int soalIndex = (int)Math.floor(Math.random()*bankSoal.size());
        modelWord = bankSoal.get(soalIndex);
        nameLabel.setVisible(true);
        messageLabel.setText("Type The Answer Of The Scribble Below");
        nameLabel.setText(modelWord.acakHuruf());
        startButton.setVisible(false);
        nameTextField.setVisible(true);
        submitButton.setVisible(true);
        nyawaLabel.setVisible(true);
        nyawa = 3;
        nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
        modelWord.setSoal(modelWord.getBasicWord());
        hintButton.setVisible(true);
        categoryButton1.setVisible(false);
        categoryButton2.setVisible(false);
        categoryButton3.setVisible(false);
        startButton.setVisible(false);

    }//GEN-LAST:event_categoryButton1ActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
        if(hintTotal>0){
            hintTotal--;
            messageLabel.setVisible(true);
            messageLabel.setText(modelWord.getHint());
            nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);}
        else{
            JOptionPane.showMessageDialog(rootPane, "Hint sudah habis");
        }
    }//GEN-LAST:event_hintButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        int soalIndex = (int)Math.floor(Math.random()*bankSoal.size());
        nameTextField.setText("");
        resetButton.setVisible(false);
        modelWord = bankSoal.get(soalIndex);
        nameLabel.setVisible(true);
        messageLabel.setText("Type The Answer Of The Scribble Below");
        nameLabel.setText(modelWord.acakHuruf());
        startButton.setVisible(false);
        nameTextField.setVisible(true);
        submitButton.setVisible(true);
        nyawaLabel.setVisible(true);
        nyawa = 3;
        nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
        modelWord.setSoal(modelWord.getBasicWord());
        hintButton.setVisible(true);
        //        ambilNama();
        //        messageLabel.setVisible(true);
        //        if(namaHasil.equalsIgnoreCase("Lionel Messi")){
            //        messageLabel.setText("The one who wins the UEFA Ballon d'Or the most");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Ricardo Kaka")){
            //        messageLabel.setText("The last AC Milan player who wins the UEFA Ballon d'Or");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Clerance Seedorf")){
            //        messageLabel.setText("The one who wins UEFA Champions League with three different teams");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Cristiano Ronaldo")){
            //        messageLabel.setText("The last winner of UEFA Ballon d'Or");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("FC Porto")){
            //        messageLabel.setText("The first team that wins the UEFA Champions League under Jose Mourinho");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Manchester United")){
            //        messageLabel.setText("The last winner of the UEFA Europa League");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Germany")){
            //        messageLabel.setText("The last winner of FIFA World Cup");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("AC Milan")){
            //        messageLabel.setText("The team that already has 7 UEFA Champions League trophy");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Leicester City")){
            //        messageLabel.setText("The winner of 2015/2016 Premier League");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Portugal")){
            //        messageLabel.setText("The last winner of FIFA Euro");
            //        }
        //        nameLabel.setText(namaAcakan);
        //        nameLabel.setVisible(true);
        //        submitButton.setVisible(true);
        //        nameTextField.setVisible(true);
        //        nameTextField.setText("");
        //        resetButton.setVisible(false);
        //        nyawaLabel.setVisible(true);
        //        nyawa = 3;
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        modelWord.setJawaban(nameTextField.getText());
        nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
        try{
            String jawaban = nameTextField.getText();
            if(nyawa==0){
                JOptionPane.showMessageDialog(rootPane, "YOU ARE VERY STUPID","GAME OVER",2);
                messageLabel.setVisible(false);
                nameTextField.setVisible(false);
                submitButton.setVisible(false);
                resetButton.setVisible(true);
                nameLabel.setText("Your chances has run out.");
                nyawa = 4;
                nyawaLabel.setVisible(false);
            }
            if(!modelWord.getJawaban().equalsIgnoreCase(modelWord.getSoal())){
                messageLabel.setText("Wrong Answer!");
                nyawa --;
                nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);

            }
            else
            {
                messageLabel.setVisible(true);
                messageLabel.setText("Right answer!");
                nameTextField.setVisible(false);
                submitButton.setVisible(false);
                resetButton.setVisible(true);
                nameLabel.setText(namaHasil);
                nyawa = 3;
                nyawaLabel.setText("Lives : "+ nyawa+" | Hint :" +hintTotal);
                hintButton.setVisible(false);
                categoryButton.setVisible(true);
                nyawaLabel.setVisible(false);
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "You need to type the answer.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:

        categoryButton1.setVisible(true);
        categoryButton2.setVisible(true);
        categoryButton3.setVisible(true);
        messageLabel.setText("Select the category.");
        startButton.setVisible(false);

        //        ambilNama();
        //        if(namaHasil.equalsIgnoreCase("Lionel Messi")){
            //        messageLabel.setText("The one who wins the UEFA Ballon d'Or the most");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Ricardo Kaka")){
            //        messageLabel.setText("The last AC Milan player who wins the UEFA Ballon d'Or");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Clerance Seedorf")){
            //        messageLabel.setText("The one who wins UEFA Champions League with three different teams");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Cristiano Ronaldo")){
            //        messageLabel.setText("The last winner of UEFA Ballon d'Or");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("FC Porto")){
            //        messageLabel.setText("The first team that wins the UEFA Champions League under Jose Mourinho");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Manchester United")){
            //        messageLabel.setText("The last winner of the UEFA Europa League");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Germany")){
            //        messageLabel.setText("The last winner of FIFA World Cup");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("AC Milan")){
            //        messageLabel.setText("The team that already has 7 UEFA Champions League trophy");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Leicester City")){
            //        messageLabel.setText("The winner of 2015/2016 Premier League");
            //        }
        //        else if(namaHasil.equalsIgnoreCase("Portugal")){
            //        messageLabel.setText("The last winner of FIFA Euro");
            //        }
        //
        //        nameLabel.setText(namaAcakan);
        //        nameLabel.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakNamaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryButton;
    private javax.swing.JButton categoryButton1;
    private javax.swing.JButton categoryButton2;
    private javax.swing.JButton categoryButton3;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nyawaLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
